# Generated by Django 2.2.5 on 2021-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('job_href', models.CharField(max_length=100)),
                ('coid', models.CharField(max_length=16)),
                ('job_name', models.CharField(max_length=64)),
                ('keyword', models.CharField(max_length=16)),
                ('companytype_text', models.CharField(max_length=64, null=True)),
                ('jobwelf_list', models.CharField(max_length=100, null=True)),
                ('degreefrom', models.CharField(max_length=8, null=True)),
                ('company_name', models.CharField(max_length=64, null=True)),
                ('attribute_text', models.CharField(max_length=64, null=True)),
                ('workyear', models.CharField(max_length=8, null=True)),
                ('companysize_text', models.CharField(max_length=20, null=True)),
                ('companyind_text', models.CharField(max_length=10, null=True)),
                ('providesalary_text', models.CharField(max_length=10, null=True)),
                ('workarea_text', models.CharField(max_length=20, null=True)),
                ('date1', models.DateTimeField()),
            ],
        ),
    ]
