# Generated by Django 3.1.7 on 2021-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210315_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('jobid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('job_href', models.CharField(max_length=100)),
                ('coid', models.CharField(max_length=16)),
                ('job_name', models.CharField(max_length=64)),
                ('keyword', models.CharField(max_length=16)),
                ('companytype_text', models.CharField(max_length=64)),
                ('jobwelf_list', models.CharField(max_length=100)),
                ('degreefrom', models.CharField(max_length=8)),
                ('company_name', models.CharField(max_length=64)),
                ('attribute_text', models.CharField(max_length=64)),
                ('workyear', models.CharField(max_length=8)),
                ('companysize_text', models.CharField(max_length=20)),
                ('companyind_text', models.CharField(max_length=30)),
                ('providesalary_text', models.CharField(max_length=10)),
                ('workarea_text', models.CharField(max_length=20)),
                ('date1', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='companyind_text',
            field=models.CharField(max_length=30),
        ),
    ]
