# Generated by Django 3.1.7 on 2021-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210318_1958'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['keyword'], name='app01_job_keyword_0376f3_idx'),
        ),
    ]
