# Generated by Django 3.1.7 on 2021-03-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210329_1240'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='app01_job_keyword_0376f3_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='attribute_text',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyind_text',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='companysize_text',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='companytype_text',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='degreefrom',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobwelf_list',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='keyword',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='providesalary_text',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='workarea_text',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='workyear',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
